name: API Deploy on Koyeb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Koyeb
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Docker
        run: docker build -t eshop-app .
      - name: Deploy through API
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEBAPITOKEN }}
          KOYEB_SERVICE_ID: f41e9cb5-bb78-40af-bb24-103a14a286c0
        run: |
          curl -X POST "https://app.koyeb.com/v1/services/$KOYEB_SERVICE_ID/redeploy" \
               -H "Authorization: Bearer $KOYEB_API_TOKEN" \
               -H "Content-Type: application/json"